### ISSUE TITLE
License contains references to yup-oauth2

### ISSUE THREAD

**Issue by djc** [hrvolapeter/gcp_auth#10]
You might want to fix that up. :)

**Comment by hrvolapeter** [comment]
The jwt file is from big part sourced from yuo-oauth2 project it seemed only fair to preserve their license (is appended at the end of the license for this crate). Even though they are licensed under the same license I don't think the license for yup-oauth can be removed. Do you have some more information about licensing practices in open-source?

**Comment by djc** [comment]
Ah, I didn't notice that you basically had multiple licenses in a single file. In that case, this is probably the right thing to do.
