### ISSUE TITLE
Exploring the possibility of making AuthenticationManager easier to use from many threads

### ISSUE THREAD

**Issue by bes** [hrvolapeter/gcp_auth#18]
Hello!

I would like to explore the possibility of making `AuthenticationManager` easier to use from multiple threads. Specifically, I want to use `AuthenticationManager` as the basis for authentication to GCP services in an async `Rocket` service.

I imagine a few ways of doing this, since the `client` property of `AuthenticationManager` prevents it from being used by multiple threads.

The point is to avoid the initialization cost of the `init()` function. Maybe you have a good reason not to do any of the below, which I would be happy to hear more about.

Some possible solutions:

# Split out client from AuthenticationManager

Instead manage a client through some other struct that exists per thread, maybe a `AuthClient` newtype. Rename `AuthenticationManager` into `TokenGenerator` maybe? `get_token` would take an `&AuthClient`.

That would enable the following use cases:

* Possible to clone `TokenGenerator` and have one per thread in thread local storage?
* Put a `TokenGenerator` in a `Mutex` or `RwLock`

One problem is that there needs to be a lock when the `refresh_token` path needs to run.

There might be other problems that I haven thought about.

# Create a new API for getting tokens asynchronously

Provide an optional feature that enables a user to get a token through a tokio channel?

# Something completely different?

Maybe you have an even better idea?

**Comment by hrvolapeter** [comment]
I can see two use cases for using `AuthenticationManager` on multiple threads:
-  require access to tokens from multiple threads at the same time e.g for high performance workloads issuing a lot of commands where we could argue that waiting for lock is negligible compared to network roundtrip
- doing async operations where everything is implicitly multi threaded (tokio)

I personally use this pattern for async applications:
```
static AUTHENTICATOR: Lazy<gcp_auth::AuthenticationManager> =
    once_cell::sync::Lazy::new(|| futures::executor::block_on(gcp_auth::init()).expect("Should set-up auth"));

async fn a() {
   let token = AUTHENTICATOR.get_token(AUTH_SCOPE).await?;
}
```

Would that fit your use case?

**Comment by bes** [comment]
Yes, that's a great pattern for async. I think I really did overthink before researching. I will edit my original question to make it easier for others to reach your answer.

Thanks!

**Comment by hrvolapeter** [comment]
@bes Maybe you could add some example in readme for other to understand better?

**Comment by bes** [comment]
I'll add something to README and make a PR.

I came up with one more question, though. What happens in the case where multiple async operations try to get an access token at the same time, but `AUTHENTICATOR` only contains an expired token?

**Comment by hrvolapeter** [comment]
In the case of an expired token all threads accessing token will wait on the `await` block and continue when there is a token available. This could be potentially optimised to do "optimistic" refresh where new token is requested on a separate thread and threads can continue using still valid and available token. Although the blocking time should be around 1ms so this might not be worth of the optimization.

**Comment by djc** [comment]
For reference, in https://draft.ryhl.io/blog/async-what-is-blocking/ Alice Ryhl (a pretty prominent member of the tokio community) says the blocking time for normal futures should be limited to about 100µs, so maybe we should have a different strategy for this.

**Comment by bes** [comment]
> In the case of an expired token all threads accessing token will wait on the `await` block and continue when there is a token available. This could be potentially optimised to do "optimistic" refresh where new token is requested on a separate thread and threads can continue using still valid and available token. Although the blocking time should be around 1ms so this might not be worth of the optimization.

OK but the check for expiredness is before the blocking call, so all of them will update the access token individually, right? So 10 threads -> 10 individual fetches -> 10x the time atually required?



> For reference, in https://draft.ryhl.io/blog/async-what-is-blocking/ Alice Ryhl (a pretty prominent member of the tokio community) says the blocking time for normal futures should be limited to about 100µs, so maybe we should have a different strategy for this.

👍

**Comment by bes** [comment]
> For reference, in https://draft.ryhl.io/blog/async-what-is-blocking/ Alice Ryhl (a pretty prominent member of the tokio community) says the blocking time for normal futures should be limited to about 100µs, so maybe we should have a different strategy for this.

I thought about this during the day, and I was thinking that this isn't a problem?

* There are no long locks/waits in the `async fn refresh_token` implementations. There is an await on a `hyper` request, which I guess should be handled "correctly" inside ?`hyper`?
* Then there's a write lock, which should finish quite fast?

It still doesn't help that multiple parallell calls to `refresh_token` leads to many http requests, though?

**Comment by djc** [comment]
Yeah, it seems like that could be more optimal.

**Comment by hrvolapeter** [comment]
@bes I'll try to check and be sure to make only one call, but that might require also synchronization between threads at least for refreshing token.

as far as it goes for the blocking time, @djc do you have some other blogs for recommendation on how long future should be suspended. I didn't see explanation in the blog from Alice and I don't see what issues suspended future could cause

**Comment by bes** [comment]
@hrvolapeter [Here is one of (many) references Alice makes to "100 microseconds" ](https://users.rust-lang.org/t/async-read-write-trait-objects-not-closing-on-connection-dropping/54399/8)

Here is the [Tokio documentation on how to think about shared state](https://tokio.rs/tokio/tutorial/shared-state)

Quote:

> If contention on a synchronous mutex becomes a problem, the best fix is rarely to switch to the Tokio mutex. Instead, options to consider are:
> 
> * Switching to a dedicated task to manage state and use message passing.
> * Shard the mutex.
> * Restructure the code to avoid the mutex.
> 

I think the best approach (after reading the docs) would be a dedicated task + message passing: https://tokio.rs/tokio/tutorial/channels

**Comment by djc** [comment]
I think the simple solution in this case might be [`spawn_blocking()`](https://docs.rs/tokio/1.1.1/tokio/runtime/struct.Handle.html#method.spawn_blocking)?

**Comment by bes** [comment]
> I think the simple solution in this case might be [`spawn_blocking()`](https://docs.rs/tokio/1.1.1/tokio/runtime/struct.Handle.html#method.spawn_blocking)?

Does that prevent multiple async fns from trying to fetch a new access token at once?
