### ISSUE TITLE
get_token never finishes

### ISSUE THREAD

**Issue by andreclaudino** [hrvolapeter/gcp_auth#21]
I am using the latest version (0.4.0)

I am getrring token from the following lines:

```rust
let authentication_manager = gcp_auth::init().await.unwrap();
authentication_manager.get_token(scopes).await.unwrap();
```

Execution never returns from this point.

**Comment by hrvolapeter** [comment]
Were you able to find cause of this? I'm not able to reproduce it. Could you maybe provide example?

**Comment by andreclaudino** [comment]
I could not investigate it enought, but looks a problem with tokio runtime. Now it is not happening, but we may try to evaluate it better, or document how to use with different runtimes avoiding these kind of problems.

**Comment by praveenperera** [comment]
I'm having this same issue, when the its wrapped in an Arc
