### ISSUE TITLE
gcloud stores application user credentials in an SQLLite database

### ISSUE THREAD

**Issue by thrykol** [hrvolapeter/gcp_auth#27]
`gcloud auth` appears to no longer write a user's application credentials to `application_default_credentials.json` but instead to a user specific path under `.config/gcloud/legacy_credentials/`.  I believe the change was done when the authors moved to use SQLite to manage the tokens.

I'd like to add support for using `gcloud auth print-access-token` directly but wanted to get feedback before committing to the process.  Are there concerns or opinions about adding support for `gcloud`?

**Comment by djc** [comment]
How would it affect the current support? Would you replace it, or add it as an alternative option?

**Comment by thrykol** [comment]
I'd give priority to using `gcloud` but keep the current option as the last ditch attempt.

**Comment by djc** [comment]
Sounds sane to me. 👍

**Comment by hrvolapeter** [comment]
Sounds like great idea, I haven't noticed they changed ADCs in the newer versions
