### ISSUE TITLE
gcp_auth::init() requires GOOGLE_APPLICATION_CREDENTIALS be defined

### ISSUE THREAD

**Issue by thrykol** [hrvolapeter/gcp_auth#28]
The absence of the environment variable `GOOGLE_APPLICATION_CREDENTIALS` should not preclude using `DefaultServiceAccount` and `DefaultAuthorizedUser`.

**Comment by djc** [comment]
Sounds good, want to submit a PR?

**Comment by thrykol** [comment]
Opened PR: https://github.com/hrvolapeter/gcp_auth/pull/29

**Comment by thrykol** [comment]
PR merged.
