### ISSUE TITLE
Make it possible to parse secrets from string or bytes rather than providing path to file

### ISSUE THREAD

**Issue by brocaar** [hrvolapeter/gcp_auth#45]
Best wishes for the New Year :fireworks: 

For one of my projects I need to generate tokens to interact with the GCP API. It looks like this is exactly what I need, especially since I'm looking for something simple instead of a full SDK.

In my case the JSON secrets file is stored in a database. Unless I have missed something, I believe reading the file from disk is currently the only option to use your library. Would you consider adding a function like:

```gcp_auth::from_credentials_str```

In this case the given string or slice of bytes already contains the content of the JSON file.

**Comment by hrvolapeter** [comment]
I think that could make sense to basically provide custom initialization method, what do you think @djc ?

**Comment by djc** [comment]
Yeah, this definitely seems reasonable to me. When implementing this, would be nice to avoid code duplication. I'd probably remove `CustomServiceAccount::from_file()` and `ApplicationCredentials::from_file()` in favor of a `CustomServiceAccount::from_json(s: &str)` (which can directly deserialize JSON -- deferring to a single-use method on `ApplicationCredentials` seems unnecessary). Then, maybe change `get_authentication_manager()` to take an `Option<PathOrStr>`.

**Comment by hrvolapeter** [comment]
@brocaar did you want to take a look at the implementation as well or should I have a look

**Comment by brocaar** [comment]
@hrvolapeter I've created the above pull-request. I'm looking forward to your feedback :)
