### ISSUE TITLE
Using `#[tracing::instrument]` on `refresh_token()` leaks sensitive information to logs

### ISSUE THREAD

**Issue by richardbrodie** [hrvolapeter/gcp_auth#55]
I have discovered a lot of entries such as the following in my log files:
```
2022-05-20T08:29:28.053898Z DEBUG refresh_token: hyper::client::connect::http: connecting to 142.250.74.138:443 self=CustomServiceAccount { credentials: ApplicationCredentials { type: Some("service_account"), ...
```

The problem here, is that `ApplicationCredentials` contains a plaintext private key which is getting printed repeatedly to our log files, as well as a lot of other information one might not choose to expose so liberally such as service-account email and id, etc.

Perhaps using something like `#[instrument(skip_all)]` would be safer in this case?

**Comment by hrvolapeter** [comment]
Thanks for the report, I'll take a look

**Comment by Wicpar** [comment]
running into the same issues, i had to disable the logs for all dependencies.
