### ISSUE TITLE
My token looks like a morse code

### ISSUE THREAD

**Issue by DiogoJunqueiraGeraldo** [hrvolapeter/gcp_auth#64]
Maybe I'm just dumb and didn't understand how to use the library. Sorry if that's the case, but I'm perplexed about this output.

![image](https://user-images.githubusercontent.com/55358500/212592619-968cfe3d-4bda-4e9c-bd95-aec9d183fd3d.png)
![image](https://user-images.githubusercontent.com/55358500/212592734-0de5de8d-eb54-4dcb-9f72-fe2bc0474fd3.png)

Output: 
ya29.c.b0AT7lpjA9DDSaBgwjFjWyjZ6iXNU3Lmok9NQmStz4hCc3RuPOw2GQB2x5rHiKqNkNyEJHlLzEUbkJ1NF_g7wNSgCXeLnLJonMLSfmi1Sr8ZrMFCG1nDZV1tymD5dnYWX2S3g2fECKqXvJrUwxDcwe2WRhuPZmse-rFTGAm3xUdk9RpLQYLpwzVHz8rLvg33ULx7agLUcuGLf81s5GW9M82PjiEcDIgjk........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by djc** [comment]
That's pretty weird, I don't know why that would happen. If you can dig in more to find the root cause, that'd be interesting!

**Comment by hrvolapeter** [comment]
Hi @DiogoJunqueiraGeraldo, Did you check if the token is actually not working?

I found similar issue [here](https://github.com/googleapis/google-api-nodejs-client/issues/2839) which mentions the dots are used as a padding since google is planing to increase the length of the tokens

**Comment by DiogoJunqueiraGeraldo** [comment]
@hrvolapeter, thank you so much for finding this!

I probably got something wrong with my pubsub configuration, but the token is working, but that's not a problem anymore. I changed my project architecture to avoid these integration issues on my rust server.

thank you so much guys for the support!

![image](https://user-images.githubusercontent.com/55358500/212979734-2c31b021-d60e-4301-9628-415fae8b4759.png)

**Comment by hrvolapeter** [comment]
No worries, seems like pretty recent change from Google. Good luck 🤞
