### ISSUE TITLE
Tokens fetched via a GCloudAuthorizedUser do not refresh

### ISSUE THREAD

**Issue by MatthewHelmer** [hrvolapeter/gcp_auth#66]
It seems that `GCloudAuthorizedUser::from_string` defaults the token's `expiry_time` to `None`, which causes `Token::has_expired` to always return false. This results in `AuthenticationManager::get_token` never refreshing a token that was retrieved via a `GCloudAuthorizedUser`.

Are these tokens not intended to be refreshed? Would it be unreasonable to default the `expiry_time` to one hour from when `from_string` is called? Something like:

`expires_at: Some(OffsetDateTime::now_utc() + Duration::hours(1))`

I don't see anything about extending the token's expiry time in the [documentation for the CLI command used to fetch the token](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/print-access-token), but I suppose it's possible the expiry time's default could be overridden somewhere else.

**Comment by djc** [comment]
Hmm, good idea to investigate this. The tokens seem to be opaque (that is, you can't decode them like a JWT) but if you call the `tokeninfo` API as suggested in the documentation you linked to you can see that the expiration time is actually an hour:

```
djc-2021 update-deps shared $ curl -H "Content-Type: application/x-www-form-urlencoded" -d "access_token=$(gcloud auth application-default print-access-token)" https://www.googleapis.com/oauth2/v1/tokeninfo

{
  "issued_to": "foobar.apps.googleusercontent.com",
  "audience": "foobar.apps.googleusercontent.com",
  "user_id": "123456789",
  "scope": "openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/accounts.reauth",
  "expires_in": 3599,
  "email": "dirkjan@example.com",
  "verified_email": true,
  "access_type": "offline"
}
```

So yeah, I agree that it would make sense to store an expiration time of one hour, and refresh them when expired. Even though that explicit expiration duration is not documented, I think we wouldn't want to implicitly incur the overhead of calling `tokeninfo` every time, and it seems likely that the default expiration time won't change that often/anytime soon.

**Comment by MatthewHelmer** [comment]
@djc I appreciate the feedback. Do you think it's worth refactoring the `expires_at` member of the `InnerToken` struct to be type `OffsetDateTime` rather than `Option<OffsetDateTime>`? I fiddled with it very briefly and noticed that doing so caused a compile error somewhere with Serde. I'll have to try it again to remind myself whether the issue was with a Serde attribute, or if it was on the `Deserialize` derive.

**Comment by MatthewHelmer** [comment]
@djc I've opened pull request #67 for this.
